name: sherlog
description: A logging package
version: 1.0.0
repository: https://github.com/TheMakersPrime/sherlog

environment:
  sdk: ^3.6.0

dependencies:
  logger: ^2.5.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
